## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [7]:
arr = np.random.randint(0,15,10)
print(arr)
mask = (arr > 3) & (arr < 8)
arr[mask] *= -1
print(arr)

[ 6 11 14  5  8  0  4  4  4  1]
[-6 11 14 -5  8  0 -4 -4 -4  1]


**2.** Заменить максимальный элемент случайного массива на 0

In [11]:
arr = np.random.randint(0,15,10)
print(arr)
arr[arr == arr.max()] = 0
print(arr)

[1 2 3 1 4 0 2 2 8 6]
[1 2 3 1 4 0 2 2 0 6]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [12]:
arr = np.random.randint(10, 50, size=(2, 3))
arrays = [row for row in arr]
combinations = np.stack(np.meshgrid(*arrays), axis=-1).reshape(-1, arr.shape[0])
print(combinations)

[[10 22]
 [22 22]
 [44 22]
 [10 19]
 [22 19]
 [44 19]
 [10 31]
 [22 31]
 [44 31]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [74]:
A = np.random.randint(10, 50, size=(8, 3))
print(A)
B = np.random.randint(10, 50, size=(2, 2))
print(B)
mask1 = np.isin(A, B[0]).any(axis=1)
mask2 = np.isin(A, B[1]).any(axis=1)
final_mask = mask1 & mask2
result = A[final_mask]
print(result)

[[23 21 30]
 [31 11 32]
 [26 27 10]
 [37 38 45]
 [13 16 19]
 [42 20 18]
 [35 33 42]
 [30 27 10]]
[[31 42]
 [31 35]]
[[31 11 32]
 [35 33 42]]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [83]:
matrix = np.random.randint(0, 4, size=(10, 3))
print(matrix)
ranges = np.ptp(matrix, axis=1)
mask = ranges > 0
result = matrix[mask]
print(result)

[[2 2 1]
 [3 0 3]
 [2 3 3]
 [1 3 2]
 [2 2 2]
 [1 1 2]
 [3 2 0]
 [1 0 2]
 [2 2 2]
 [0 0 2]]
[[2 2 1]
 [3 0 3]
 [2 3 3]
 [1 3 2]
 [1 1 2]
 [3 2 0]
 [1 0 2]
 [0 0 2]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [103]:
arr = np.random.randint(0,4, size=(4,3))
print(arr)
arr_unique = np.unique(arr, axis=0)
print(arr_unique)

[[3 2 1]
 [1 1 1]
 [1 1 1]
 [3 2 2]]
[[1 1 1]
 [3 2 1]
 [3 2 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [106]:
X_list = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]

def prod_diag_non_numpy(matrix):
    prod = 1
    d_len = min(len(matrix), len(matrix[0]))

    for i in range(d_len):
        if matrix[i][i] != 0:
            prod *= matrix[i][i]
    return prod
print(prod_diag_non_numpy(X_list))

X_numpy = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
result = np.diag(X_numpy)[np.diag(X_numpy) != 0].prod()
print(result)

3
3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [6]:
X_array = [1, 2, 2, 4]
Y_array = [4, 2, 1, 2]

def are_multisets_equal_not_numpy(list1, list2):
    if len(list1) != len(list2):
        return False
    else:
        return sorted(list1) == sorted(list2)
print(are_multisets_equal_not_numpy(X_array, Y_array))

X_numpy = np.array([1, 2, 2, 4])
Y_numpy = np.array([4, 2, 1, 2])

def are_multisets_equal_numpy(list1, list2):
    if len(list1) != len(list2):
        return False
    else:
        return (np.sort(list1) == np.sort(list2)).all()

print(are_multisets_equal_numpy(X_numpy, Y_numpy))

True
True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [8]:
X_list = [6, 2, 0, 3, 0, 0, 5, 7, 0]

def max_after_zero_not_numpy(arr):
    numbers = []
    for i in range(len(arr) - 1):
        if arr[i] == 0:
            numbers.append(arr[i+1])
    return max(numbers) if numbers else None
print(max_after_zero_not_numpy(X_list))

X_numpy = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
res = X_numpy[1:][(X_numpy == 0)[:-1]].max()
print(res)

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [21]:
X_list = [2, 2, 2, 3, 3, 3, 5]
def count_in_list_not_numpy(arr):
    num = []
    count = []
    for i in range(len(arr)):
        if arr[i] not in num:
            num.append(arr[i])
            count.append(arr.count(arr[i]))
    return (num, count)
print(count_in_list_not_numpy(X_list))

x_numpy = np.array([2, 2, 2, 3, 3, 3, 5])

def rle_numpy(x):
  change_mask = np.append(True, x[1:] != x[:-1])
  run_starts_indices = np.where(change_mask)[0]
  values = x[run_starts_indices]
  counts = np.diff(np.append(run_starts_indices, x.size))
  
  return (values, counts)

print(rle_numpy(x_numpy))
        

([2, 3, 5], [3, 3, 1])
(array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [22]:
import math

X_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 1, 1]]
Y_list = [[0, 0, 0], [1, 2, 4]]

def cdist_non_numpy(X, Y):
  dist_matrix = []
  for x_vec in X:
    row = []
    for y_vec in Y:
      sum_of_squares = sum([(x_k - y_k)**2 for x_k, y_k in zip(x_vec, y_vec)])
      row.append(math.sqrt(sum_of_squares))
    dist_matrix.append(row)
  return dist_matrix

for row in cdist_non_numpy(X_list, Y_list):
    print([round(val, 2) for val in row])
    
X_np = np.array(X_list)
Y_np = np.array(Y_list)

def cdist_numpy(X, Y):
  sum_X_sq = np.sum(X**2, axis=1, keepdims=True)
  sum_Y_sq = np.sum(Y**2, axis=1)                
  neg_2XY = -2 * X @ Y.T                       
  dist_sq = sum_X_sq + neg_2XY + sum_Y_sq
  return np.sqrt(np.maximum(0, dist_sq))

print(np.round(cdist_numpy(X_np, Y_np), 2))

[3.74, 1.0]
[8.77, 4.69]
[13.93, 9.85]
[1.73, 3.16]
[[ 3.74  1.  ]
 [ 8.77  4.69]
 [13.93  9.85]
 [ 1.73  3.16]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [23]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [24]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [25]:
average_calories = np.mean(calorie_stats)
difference = average_calories - 60
print(average_calories)
print(difference)

106.88311688311688
46.883116883116884


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [26]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [27]:
median_calories = np.median(calorie_stats)
print(median_calories)
print(average_calories)

110.0
106.88311688311688


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [28]:
p_3 = np.percentile(calorie_stats, 3)
p_4 = np.percentile(calorie_stats, 4)
print({p_3})
print({p_4})
nth_percentile = 4

{np.float64(55.599999999999994)}
{np.float64(70.0)}


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [29]:
more_calories_count = np.sum(calorie_stats > 60)
total_count = calorie_stats.size
more_calories_percentage = (more_calories_count / total_count * 100)

print(more_calories_percentage)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [30]:
calorie_std = np.std(calorie_stats)
print(calorie_std)

19.35718533390827


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [31]:
'''Средняя калорийность хлопьев у конкурентов составляет **107 калорий**, это почти вдвое выше, чем у CrunchieMunchies. 96% всех проанализированных хлопьев имеют более высокую калорийность, чем наш продукт. CrunchieMunchies входят в топ-4% самых низкокалорийных хлопьев'''

'Средняя калорийность хлопьев у конкурентов составляет **107 калорий**, это почти вдвое выше, чем у CrunchieMunchies. 96% всех проанализированных хлопьев имеют более высокую калорийность, чем наш продукт. CrunchieMunchies входят в топ-4% самых низкокалорийных хлопьев'